name: CI/CD

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:

  deploy:
    name: Create new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push' &&  github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Dry bump version
      id: dry-bump-tag
      uses: anothrNick/github-tag-action@1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DRY_RUN: true
        DEFAULT_BUMP: patch

    - name: Commit the new version of the package
      env:
        NEW_TAG: ${{ steps.dry-bump-tag.outputs.new_tag }}
      run: |
        git config user.name "GitHub Actions Bot"
        sed -i "s/^version = .*/version = \"${NEW_TAG}\"/" pyproject.toml
        sed -i "s/^__version__ = .*/__version__ = \"${NEW_TAG}\"/" dstaf/__init__.py
        git add pyproject.toml dstaf/__init__.py
        git commit -m "[tag] version ${NEW_TAG}"
        git push origin master

    - name: Push tag
      id: push-tag
      uses: anothrNick/github-tag-action@1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
