name: PR Checks

on:
  push:
    branches:
      - master  # Only run when target is master
    tags:
      - '*'
  pull_request:
    types:
      - opened  # Only run when a PR is opened


jobs:

  check-title:
    name: Check PR for Version Tag
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
      - name: Validate Pull Request Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ ! "$PR_TITLE" =~ ^(Major|Minor|Patch|Doc) ]]; then
            echo "Error: Pull request title must start with 'Major', 'Minor', 'Patch', or 'Doc'."
            echo "     - '$PR_TITLE'"
            exit 1
          fi

  analyze:
    name: Code Analysis
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Code Analysis Requirements
      run: |
        pip install --upgrade bandit pylint 

    - name: Vulnerability Scan
      run: |
        bandit dstaf -r -v -n 3 --severity-level=all

    - name: Lint Scan
      run: |
        pylint dstaf/*py
