name: PR Checks

permissions:
  security-events: write
  actions: read
  contents: read

on:
  push:
    branches:
      - master  # Only run when target is master
    tags:
      - '*'
  pull_request:

jobs:

  requirements:
    name: Requirement Audit
    runs-on: ubuntu-latest
    if: github.event_name != 'push' && github.event.pull_request.merged == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JWT Generation Requirement
        env:
          DASHABOT_APPID: ${{ secrets.DASHABOT_APPID }}
          DASHABOT_IID: ${{ secrets.DASHABOT_IID }}
        run: |
          pip install --upgrade .[cicd]
          echo "${{ secrets.DASHABOT_PK }}" | python3 .github/generate_jwt.py
          echo "Token Requirement OK"

      - name: Check Token Availability
        run: |
          if [[ "{{ $env.GH_TOKEN }}" == "{{ $env.GITHUB_TOKEN }}" ]]; then
            echo "GH Token not set or incorrectly paired"
            exit 1
          fi
          if [[ "{{ $env.GH_TOKEN }}" == "" ]]; then
            echo "GH_TOKEN empty"
            exit 1
          fi
          if [[ "{{ $env.GITHUB_TOKEN }}" == "" ]]; then
            echo "GITHUB_TOKEN empty"
            exit 1
          fi
          echo "Tokens Check out OK"

      - name: Version Requirement
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          if [[ ! "$PR_TITLE" =~ ^(Major|Minor|Patch|Doc|Auto) ]]; then
            echo "Error: Pull request title must start with 'Major', 'Minor', 'Patch', or 'Doc'."
            echo "  〰️ Branch Name: '$BRANCH_NAME', ❌ PR Title: '$PR_TITLE'"
            echo "     You need to create a new pull request, or commit a change for this test to run again."
            exit 1
          fi
          if [[ "$PR_TITLE" =~ ^Auto ]] && [[ ! "$BRANCH_NAME" =~ ^gh-actions ]]; then
            echo "Error: Auto labelled PRs must only be created by GitHub Actions. Your PR must start with a version semaphore. See https://semver.org/ for definitions."
            echo "  ✔️ Branch Name: '$BRANCH_NAME', ❌ PR Title: '$PR_TITLE'"
            echo "     You need to create a new pull request, or commit a change for this test to run again."
            exit 1
          fi
          if [[ "$PR_TITLE" =~ ^(Major|Minor|Patch|Doc) ]] && [[ "$BRANCH_NAME" =~ ^gh-actions ]]; then
            echo "Error: Branches starting with 'gh-actions' are only to be opened by Create Release action. Rename your branch."
            echo "  ❌ Branch Name: '$BRANCH_NAME', ✔️ PR Title: '$PR_TITLE'"
            echo "     You must rename your branch and submit a new commit for this test to run again."
            exit 1
          fi

  analyze:
    name: Code Analysis
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Requirements
      run: |
        pip install --upgrade .[test]

    - name: Bandit Vulnerability Scan
      run: |
        bandit dstaf -r -v -n 3 --severity-level=all

    - name: Check Optimised Imports
      run: |
        isort --check-only dstaf -v

    - name: Check Black Formatting
      run: |
        black dstaf/*py --check -t py39

    - name: Lint Scan
      run: |
        pylint dstaf/*py --py-version "3.9"

    - name: Perform Unit Tests
      run: |
        pytest
