name: CI/CD

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:

  release:
    name: Create New Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push' &&  github.ref == 'refs/heads/master'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate Release Notes
      uses: johnyherangi/create-release-notes@main
      id: create-release-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Increment Version
      id: dry-bump-tag
      uses: anothrNick/github-tag-action@1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DRY_RUN: true
        DEFAULT_BUMP: patch

    - name: Update Version Strings
      env:
        NEW_TAG: ${{ steps.dry-bump-tag.outputs.new_tag }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "gh_actions@dashasierra.com"
        sed -i "s/^version = .*/version = \"${NEW_TAG}\"/" pyproject.toml
        sed -i "s/^__version__ = .*/__version__ = \"${NEW_TAG}\"/" dstaf/__init__.py
        git add pyproject.toml dstaf/__init__.py
        git commit -m "Bump Version to ${NEW_TAG}"
        git push origin master

    - name: Checkout for Release
      uses: actions/checkout@v4

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ steps.dry-bump-tag.outputs.new_tag }}" \
          --repo="${{ github.repository }}" \
          --title="Release ${{ steps.dry-bump-tag.outputs.new_tag }}" \
          --generate-notes

    - name: Extract major version
      id: major-version
      run: echo "major=v$(echo ${{ steps.dry-bump-tag.outputs.new_tag }} | cut -d. -f1)" >> $GITHUB_ENV

    - name: Checkout for Major Tag
      uses: actions/checkout@v4

    - name: Create or update major version tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag -f "$major"
        git push -f origin "$major"