name: CI/CD

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:

  release:
    name: Create New Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push' &&  github.ref == 'refs/heads/master'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Increment Version
      id: bump-tag
      uses: anothrNick/github-tag-action@1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DRY_RUN: true
        DEFAULT_BUMP: patch

    - name: Update Version Strings
      env:
        NEW_TAG: ${{ steps.bump-tag.outputs.new_tag }}
      run: |
        git config user.name "GitHub Actions[Bot]"
        git config user.email "gh_actions@dashasierra.com"
        sed -i "s/^version = .*/version = \"${NEW_TAG}\"/" pyproject.toml
        sed -i "s/^__version__ = .*/__version__ = \"${NEW_TAG}\"/" dstaf/__init__.py
        git add pyproject.toml dstaf/__init__.py
        git commit -m "Bump Version to ${NEW_TAG}"
        git push origin master

    - name: Checkout for Tag
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Extract major, minor, patch v-versions
      id: major-version
      run: |
        echo "vmajor=v$(echo ${{ steps.bump-tag.outputs.new_tag }} | cut -d. -f1)" >> $GITHUB_ENV
        echo "vminor=v$(echo ${{ steps.bump-tag.outputs.new_tag }} | cut -d. -f1,2)" >> $GITHUB_ENV
        echo "vpatch=v$(echo ${{ steps.bump-tag.outputs.new_tag }} | cut -d. -f1,2,3)" >> $GITHUB_ENV
    - name: Create or update tags
      env:
        GITHUB_TOKEN: ${{ secrets.DSS_TOKEN }}
      run: |
        git tag -f "$vmajor"
        git push -f origin "$vmajor"
        git tag -f "$vminor"
        git push -f origin "$vminor"
        git tag -f "$vpatch"
        git push -f origin "$vpatch"

    - name: Checkout for Release
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.DSS_TOKEN }}
      run: |
        gh release create "${{ steps.bump-tag.outputs.new_tag }}" \
          --repo="${{ github.repository }}" \
          --title="DStaf ${{ steps.bump-tag.outputs.new_tag }}" \
          --generate-notes

  check-title:
    name: Version Check
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
      - name: Validate Pull Request Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ ! "$PR_TITLE" =~ ^#(major|minor|patch|none) ]]; then
            echo "Error: Pull request title must start with #major, #minor, #patch, or #none."
            exit 1
          fi
